import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

type AutomationJob = {
  id: string
  applicant_id: string
  workflow_run_id: string | null
  job_type: string
  job_label: string
  job_status: string
  priority: number
  scheduled_for: string
  attempts: number
  last_error: string | null
  payload: Record<string, unknown>
  applicants?: {
    full_name?: string
    current_stage?: string
    jobs?: { title?: string }
  }
}

type NotificationRow = {
  id: string
  applicant_id?: string
  recipient: string
  subject: string | null
  message: string
  metadata?: Record<string, unknown>
  applicants?: {
    full_name?: string
  }
}

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return Response.json(body, { status, headers: corsHeaders })
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error)
}

function processedEventForJob(job: AutomationJob, provider = 'placeholder') {
  const eventMap: Record<string, [string, string, string]> = {
    send_confirmation_sms: ['confirmation_sms_sent', 'Confirmation SMS Sent', 'Placeholder SMS confirmation was marked as sent.'],
    send_confirmation_email: ['confirmation_email_sent', 'Confirmation Email Sent', 'Placeholder email confirmation was marked as sent.'],
    parse_resume: ['resume_screened', 'Resume Screened', 'Placeholder resume parsing completed and candidate moved forward.'],
    send_ai_assessment: ['ai_assessment_sent', 'AI Assessment Sent', 'Placeholder AI screening assessment invite was queued for the candidate.'],
    evaluate_ai_assessment: ['ai_screening_evaluated', 'AI Screening Evaluated', 'Placeholder AI screening evaluation generated structured candidate scores.'],
    verify_license: ['license_verification_completed', 'License Verification Completed', 'Placeholder license verification completed.'],
    send_scheduling_link: ['scheduling_link_sent', 'Scheduling Link Sent', 'Placeholder scheduling link was marked as sent.'],
    voice_interview_analysis: ['voice_interview_analyzed', 'Voice Interview Analyzed', 'Placeholder voice interview analysis completed.'],
  }
  const [type, label, description] = eventMap[job.job_type] ?? [
    'automation_job_processed',
    'Automation Job Processed',
    'Placeholder automation job completed.',
  ]

  return {
    applicant_id: job.applicant_id,
    event_type: type,
    event_status: 'complete',
    event_label: label,
    metadata: {
      automationJobId: job.id,
      jobType: job.job_type,
      description,
      processor: 'supabase_edge_function',
      provider,
    },
  }
}

function emailHtml(notification: NotificationRow) {
  const assessmentUrl = typeof notification.metadata?.assessmentUrl === 'string'
    ? notification.metadata.assessmentUrl
    : ''
  const actionButton = assessmentUrl
    ? `<a href="${assessmentUrl}" style="display:inline-block;background:#0084ff;color:#ffffff;text-decoration:none;font-weight:700;border-radius:8px;padding:12px 18px;margin:4px 0 18px;">Complete screening assessment</a>`
    : ''

  return `
    <div style="margin:0;padding:0;background:#f8fafc;font-family:Arial,sans-serif;color:#111827;">
      <div style="max-width:640px;margin:0 auto;padding:32px 20px;">
        <div style="background:#09090b;color:#fff;border-radius:12px 12px 0 0;padding:20px 24px;">
          <div style="font-size:18px;font-weight:700;">ViankaX Hiring Automation</div>
          <div style="margin-top:6px;color:#a1a1aa;font-size:13px;">Applicant workflow update</div>
        </div>
        <div style="background:#ffffff;border:1px solid #e5e7eb;border-top:0;border-radius:0 0 12px 12px;padding:24px;">
          <h1 style="font-size:22px;line-height:1.3;margin:0 0 12px;">${notification.subject ?? 'Your application update'}</h1>
          <p style="font-size:15px;line-height:1.7;margin:0 0 18px;color:#374151;">${notification.message}</p>
          ${actionButton}
          <div style="border-top:1px solid #e5e7eb;margin-top:24px;padding-top:16px;color:#6b7280;font-size:13px;line-height:1.6;">
            This message was generated by the ViankaX Hiring Automation Platform.
          </div>
        </div>
      </div>
    </div>
  `
}

async function sendResendEmail(notification: NotificationRow) {
  const resendApiKey = Deno.env.get('RESEND_API_KEY')
  const resendFromEmail = Deno.env.get('RESEND_FROM_EMAIL') ?? 'ViankaX Hiring <onboarding@resend.dev>'
  const replyTo = Deno.env.get('RESEND_REPLY_TO')

  if (!resendApiKey) {
    return {
      sent: false,
      providerMessageId: null,
      provider: 'placeholder',
      note: 'RESEND_API_KEY is not configured; placeholder email send was used.',
    }
  }

  const emailBody: Record<string, unknown> = {
    from: resendFromEmail,
    to: notification.recipient,
    subject: notification.subject ?? 'ViankaX Hiring Automation',
    text: notification.message,
    html: emailHtml(notification),
  }

  if (replyTo) {
    emailBody.reply_to = replyTo
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(emailBody),
  })

  const result = await response.json()
  if (!response.ok) {
    throw new Error(result?.message ?? 'Resend email request failed.')
  }

  return {
    sent: true,
    providerMessageId: result?.id ?? null,
    provider: 'resend',
    note: 'Email sent with Resend.',
  }
}

async function updateWorkflowAfterJob(supabase: ReturnType<typeof createClient>, workflowRunId: string | null) {
  if (!workflowRunId) return

  const { data: jobs, error } = await supabase
    .from('automation_jobs')
    .select('job_status')
    .eq('workflow_run_id', workflowRunId)

  if (error) throw error

  const hasQueued = jobs.some((job) => job.job_status === 'queued' || job.job_status === 'running')
  const hasBlocked = jobs.some((job) => job.job_status === 'blocked')
  const nextStatus = hasBlocked ? 'blocked' : hasQueued ? 'running' : 'completed'

  const { error: workflowError } = await supabase
    .from('workflow_runs')
    .update({
      run_status: nextStatus,
      current_step: nextStatus === 'completed' ? 'completed' : 'automation_processing',
      completed_at: nextStatus === 'completed' ? new Date().toISOString() : null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', workflowRunId)

  if (workflowError) throw workflowError
}

async function applyPlaceholderJobEffects(supabase: ReturnType<typeof createClient>, job: AutomationJob) {
  const now = new Date().toISOString()
  const effects = []
  let provider = 'placeholder'

  if (job.job_type === 'send_confirmation_sms') {
    effects.push(
      supabase
        .from('notification_queue')
        .update({ notification_status: 'sent', sent_at: now, updated_at: now })
        .eq('applicant_id', job.applicant_id)
        .eq('channel', 'sms')
        .eq('notification_status', 'queued'),
    )
  }

  if (job.job_type === 'send_confirmation_email' || job.job_type === 'send_ai_assessment') {
    const { data: notifications, error: notificationError } = await supabase
      .from('notification_queue')
      .select('id, recipient, subject, message, metadata')
      .eq('applicant_id', job.applicant_id)
      .eq('channel', 'email')
      .eq('notification_status', 'queued')
      .limit(1)

    if (notificationError) throw notificationError
    const notification = notifications?.[0] as NotificationRow | undefined

    if (notification) {
      const emailResult = await sendResendEmail(notification)
      provider = emailResult.provider
      effects.push(
        supabase
          .from('notification_queue')
          .update({
            notification_status: 'sent',
            sent_at: now,
            provider_message_id: emailResult.providerMessageId,
            metadata: {
              ...(notification.metadata ?? {}),
              provider: emailResult.provider,
              note: emailResult.note,
            },
            updated_at: now,
          })
          .eq('id', notification.id),
      )
    }
  }

  if (job.job_type === 'parse_resume') {
    effects.push(
      supabase
        .from('applicants')
        .update({
          current_stage: 'Resume Screened',
          status: 'Qualified',
          updated_at: now,
        })
        .eq('id', job.applicant_id)
        .eq('current_stage', 'New Applicant'),
    )
    effects.push(
      supabase
        .from('pipeline_stage_history')
        .insert({
          applicant_id: job.applicant_id,
          from_stage: 'New Applicant',
          to_stage: 'Resume Screened',
          changed_by: 'edge_function_processor',
          reason: 'Placeholder resume parsing completed.',
        }),
    )
  }

  if (job.job_type === 'evaluate_ai_assessment') {
    effects.push(
      supabase
        .from('ai_screening_tasks')
        .update({
          task_status: 'completed',
          ai_summary: 'Placeholder AI screening found solid role fit, professional communication, and workable availability. Review risk flags before advancing.',
          role_fit_score: 84,
          professionalism_score: 86,
          communication_score: 82,
          availability_score: 80,
          risk_flags: [],
          recommendation: 'Qualified',
          completed_at: now,
          updated_at: now,
        })
        .eq('applicant_id', job.applicant_id)
        .in('task_status', ['queued', 'running']),
    )
    effects.push(
      supabase
        .from('candidate_scores')
        .update({
          screening_score: 84,
          overall_candidate_score: 86,
          updated_at: now,
        })
        .eq('applicant_id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('ai_recommendations')
        .update({
          recommendation: 'Qualified',
          confidence: 86,
          summary: 'Placeholder AI screening indicates the candidate is qualified for HR review, pending compliance and interview steps.',
          risk_flags: [],
          updated_at: now,
        })
        .eq('applicant_id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('applicants')
        .update({
          current_stage: 'Assessment Completed',
          status: 'Qualified',
          updated_at: now,
        })
        .eq('id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('pipeline_stage_history')
        .insert({
          applicant_id: job.applicant_id,
          from_stage: job.applicants?.current_stage ?? null,
          to_stage: 'Assessment Completed',
          changed_by: 'edge_function_processor',
          reason: 'Placeholder AI screening evaluation completed.',
        }),
    )
  }

  if (job.job_type === 'verify_license') {
    effects.push(
      supabase
        .from('applicants')
        .update({
          current_stage: 'License Verified',
          license_status: 'Verified',
          status: 'Qualified',
          updated_at: now,
        })
        .eq('id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('pipeline_stage_history')
        .insert({
          applicant_id: job.applicant_id,
          from_stage: job.applicants?.current_stage ?? null,
          to_stage: 'License Verified',
          changed_by: 'edge_function_processor',
          reason: 'Placeholder license verification completed.',
        }),
    )
  }

  if (job.job_type === 'voice_interview_analysis') {
    const voiceScore = 88
    effects.push(
      supabase
        .from('voice_interviews')
        .insert({
          applicant_id: job.applicant_id,
          provider: 'voice_ai_placeholder',
          recording_url: 'https://example.com/voice-interview-placeholder',
          transcript: 'Placeholder voice interview completed. Candidate communicated clearly, confirmed availability, and gave professional responses suitable for final HR review.',
          score: voiceScore,
          recommendation: 'Proceed to final in-person interview',
          status: 'Complete',
          completed_at: now,
        }),
    )
    effects.push(
      supabase
        .from('candidate_scores')
        .update({
          voice_interview_score: voiceScore,
          overall_candidate_score: voiceScore,
          updated_at: now,
        })
        .eq('applicant_id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('applicants')
        .update({
          current_stage: 'Voice Interview Complete',
          interview_status: 'Complete',
          status: 'Qualified',
          updated_at: now,
        })
        .eq('id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('pipeline_stage_history')
        .insert({
          applicant_id: job.applicant_id,
          from_stage: job.applicants?.current_stage ?? null,
          to_stage: 'Voice Interview Complete',
          changed_by: 'edge_function_processor',
          reason: 'Placeholder voice interview analysis completed automatically.',
        }),
    )
  }

  if (job.job_type === 'send_scheduling_link') {
    const scheduledFor = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString()
    effects.push(
      supabase
        .from('interview_schedules')
        .insert({
          applicant_id: job.applicant_id,
          provider: 'calendar_placeholder',
          scheduled_for: scheduledFor,
          scheduling_url: 'https://cal.com/viankax/final-interview-placeholder',
          status: 'Scheduled',
          updated_at: now,
        }),
    )
    effects.push(
      supabase
        .from('applicants')
        .update({
          current_stage: 'Interview Scheduled',
          interview_status: 'Scheduled',
          status: 'Qualified',
          updated_at: now,
        })
        .eq('id', job.applicant_id),
    )
    effects.push(
      supabase
        .from('pipeline_stage_history')
        .insert({
          applicant_id: job.applicant_id,
          from_stage: job.applicants?.current_stage ?? null,
          to_stage: 'Interview Scheduled',
          changed_by: 'edge_function_processor',
          reason: 'Final in-person interview was scheduled automatically.',
        }),
    )
  }

  effects.push(supabase.from('automation_events').insert(processedEventForJob(job, provider)))

  const results = await Promise.all(effects)
  const effectError = results.find((result) => result.error)?.error
  if (effectError) throw effectError
}

async function hasSubmittedAiAssessment(supabase: ReturnType<typeof createClient>, applicantId: string) {
  const { data, error } = await supabase
    .from('screening_answers')
    .select('id')
    .eq('applicant_id', applicantId)
    .eq('category', 'ai_assessment')
    .limit(1)

  if (error) throw error
  return Boolean(data?.length)
}

async function deferAiAssessmentEvaluation(supabase: ReturnType<typeof createClient>, job: AutomationJob) {
  const nextCheckAt = new Date(Date.now() + 10 * 60 * 1000).toISOString()
  const { error } = await supabase
    .from('automation_jobs')
    .update({
      job_status: 'queued',
      scheduled_for: nextCheckAt,
      last_error: 'Waiting for applicant to complete AI screening assessment.',
      updated_at: new Date().toISOString(),
    })
    .eq('id', job.id)

  if (error) throw error
  await updateWorkflowAfterJob(supabase, job.workflow_run_id)

  return {
    processed: false,
    message: 'AI screening evaluation is waiting for applicant answers. The job was deferred.',
    job: {
      id: job.id,
      type: job.job_type,
      label: job.job_label,
      status: 'queued',
      scheduledFor: nextCheckAt,
      applicantName: job.applicants?.full_name ?? 'Unknown applicant',
    },
  }
}

async function deferAutomationJob(supabase: ReturnType<typeof createClient>, job: AutomationJob, reason: string) {
  const nextCheckAt = new Date(Date.now() + 10 * 60 * 1000).toISOString()
  const { error } = await supabase
    .from('automation_jobs')
    .update({
      job_status: 'queued',
      scheduled_for: nextCheckAt,
      last_error: reason,
      updated_at: new Date().toISOString(),
    })
    .eq('id', job.id)

  if (error) throw error
  await updateWorkflowAfterJob(supabase, job.workflow_run_id)

  return {
    processed: false,
    message: `${job.job_label} is waiting. ${reason}`,
    job: {
      id: job.id,
      type: job.job_type,
      label: job.job_label,
      status: 'queued',
      scheduledFor: nextCheckAt,
      applicantName: job.applicants?.full_name ?? 'Unknown applicant',
    },
  }
}

async function processOrphanedEmailNotification(supabase: ReturnType<typeof createClient>) {
  const now = new Date().toISOString()
  const { data: notifications, error } = await supabase
    .from('notification_queue')
    .select('id, applicant_id, recipient, subject, message, metadata, created_at, applicants(full_name)')
    .eq('channel', 'email')
    .eq('notification_status', 'queued')
    .order('created_at', { ascending: true })
    .limit(1)

  if (error) throw error
  const notification = notifications?.[0] as NotificationRow | undefined

  if (!notification) {
    return jsonResponse({ processed: false, message: 'No queued automation jobs or email notifications are ready.' })
  }

  const emailResult = await sendResendEmail(notification)
  const { error: notificationError } = await supabase
    .from('notification_queue')
    .update({
      notification_status: 'sent',
      sent_at: now,
      provider_message_id: emailResult.providerMessageId,
      metadata: {
        ...(notification.metadata ?? {}),
        provider: emailResult.provider,
        note: `${emailResult.note} Recovered queued notification without a ready automation job.`,
      },
      updated_at: now,
    })
    .eq('id', notification.id)

  if (notificationError) throw notificationError

  const { error: eventError } = await supabase
    .from('automation_events')
    .insert({
      applicant_id: notification.applicant_id,
      event_type: 'orphaned_email_notification_processed',
      event_status: 'complete',
      event_label: 'Queued Email Notification Processed',
      metadata: {
        notificationId: notification.id,
        template: notification.metadata?.template ?? 'email_notification',
        provider: emailResult.provider,
        description: 'Recovered an email notification that was queued without a ready automation job.',
      },
    })

  if (eventError) throw eventError

  return jsonResponse({
    processed: true,
    message: `Queued email notification processed for ${notification.applicants?.full_name ?? notification.recipient}.`,
    notification: {
      id: notification.id,
      provider: emailResult.provider,
      providerMessageId: emailResult.providerMessageId,
    },
  })
}

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

    if (!supabaseUrl || !serviceRoleKey) {
      throw new Error('Missing Supabase function environment variables.')
    }

    const supabase = createClient(supabaseUrl, serviceRoleKey)
    const body = await request.json().catch(() => ({}))
    const maxJobs = Math.min(Math.max(Number(body?.maxJobs ?? 10), 1), 25)
    const processedJobs: Array<Record<string, unknown>> = []
    const deferredJobs: Array<Record<string, unknown>> = []

    for (let index = 0; index < maxJobs; index += 1) {
      const now = new Date().toISOString()
      const { data: jobs, error: jobError } = await supabase
        .from('automation_jobs')
        .select(`
          id,
          applicant_id,
          workflow_run_id,
          job_type,
          job_label,
          job_status,
          priority,
          scheduled_for,
          attempts,
          last_error,
          payload,
          applicants(full_name, current_stage, jobs(title))
        `)
        .eq('job_status', 'queued')
        .lte('scheduled_for', now)
        .order('priority', { ascending: true })
        .order('scheduled_for', { ascending: true })
        .limit(1)

      if (jobError) throw jobError
      const job = jobs?.[0] as AutomationJob | undefined

      if (!job) {
        if (!processedJobs.length && !deferredJobs.length) {
          return processOrphanedEmailNotification(supabase)
        }
        break
      }

      if (job.job_type === 'evaluate_ai_assessment' && !(await hasSubmittedAiAssessment(supabase, job.applicant_id))) {
        deferredJobs.push(await deferAiAssessmentEvaluation(supabase, job))
        continue
      }

      if (
        ['voice_interview_analysis', 'send_scheduling_link'].includes(job.job_type) &&
        !(await hasSubmittedAiAssessment(supabase, job.applicant_id))
      ) {
        deferredJobs.push(await deferAutomationJob(supabase, job, 'Waiting for applicant to complete AI screening assessment.'))
        continue
      }

      const { error: runningError } = await supabase
        .from('automation_jobs')
        .update({
          job_status: 'running',
          attempts: (job.attempts ?? 0) + 1,
          updated_at: now,
        })
        .eq('id', job.id)

      if (runningError) throw runningError

      try {
        await applyPlaceholderJobEffects(supabase, job)

        const { error: completedError } = await supabase
          .from('automation_jobs')
          .update({
            job_status: 'completed',
            last_error: null,
            updated_at: new Date().toISOString(),
          })
          .eq('id', job.id)

        if (completedError) throw completedError
        await updateWorkflowAfterJob(supabase, job.workflow_run_id)

        processedJobs.push({
          id: job.id,
          type: job.job_type,
          label: job.job_label,
          status: 'completed',
          applicantName: job.applicants?.full_name ?? 'Unknown applicant',
        })
      } catch (processError) {
        await supabase
          .from('automation_jobs')
          .update({
            job_status: 'failed',
            last_error: errorMessage(processError),
            updated_at: new Date().toISOString(),
          })
          .eq('id', job.id)

        await updateWorkflowAfterJob(supabase, job.workflow_run_id)
        throw processError
      }
    }

    return jsonResponse({
      processed: processedJobs.length > 0,
      processedCount: processedJobs.length,
      deferredCount: deferredJobs.length,
      message: processedJobs.length
        ? `Processed ${processedJobs.length} automation job${processedJobs.length === 1 ? '' : 's'}.`
        : deferredJobs.length
          ? `Deferred ${deferredJobs.length} automation job${deferredJobs.length === 1 ? '' : 's'} waiting for applicant action.`
          : 'No queued automation jobs are ready.',
      jobs: processedJobs,
      deferredJobs,
    })
  } catch (error) {
    return jsonResponse({ processed: false, error: errorMessage(error) }, 500)
  }
})
