import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

type CalendarConnection = {
  provider: string
  provider_account_email: string | null
  access_token: string | null
  refresh_token: string | null
  expires_at: string | null
}

type InterviewSchedule = {
  id: string
  applicant_id: string
  provider: string | null
  scheduled_for: string | null
  status: string
  sync_status: string | null
  external_event_id: string | null
  scheduling_url: string | null
  interviewer_email: string | null
  interview_duration_minutes: number | null
  buffer_minutes: number | null
  applicants?: {
    full_name?: string
    email?: string
    phone?: string
    jobs?: { title?: string; location?: string }
  }
}

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return Response.json(body, { status, headers: corsHeaders })
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error)
}

function providerFromSchedule(schedule: InterviewSchedule) {
  const provider = String(schedule.provider ?? '').toLowerCase()
  if (provider.includes('google')) return 'google'
  if (provider.includes('microsoft') || provider.includes('outlook')) return 'microsoft'
  return 'internal'
}

function googleTokenSecrets() {
  return {
    clientId: Deno.env.get('GOOGLE_CALENDAR_CLIENT_ID'),
    clientSecret: Deno.env.get('GOOGLE_CALENDAR_CLIENT_SECRET'),
  }
}

async function refreshGoogleToken(supabase: ReturnType<typeof createClient>, connection: CalendarConnection) {
  if (!connection.refresh_token) return connection

  const expiresAt = connection.expires_at ? new Date(connection.expires_at).getTime() : 0
  if (expiresAt > Date.now() + 60 * 1000 && connection.access_token) return connection

  const secrets = googleTokenSecrets()
  if (!secrets.clientId || !secrets.clientSecret) return connection

  const body = new URLSearchParams({
    client_id: secrets.clientId,
    client_secret: secrets.clientSecret,
    refresh_token: connection.refresh_token,
    grant_type: 'refresh_token',
  })

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  })
  const result = await response.json()

  if (!response.ok) {
    throw new Error(result?.error_description ?? result?.error ?? 'Google token refresh failed.')
  }

  const updatedConnection = {
    ...connection,
    access_token: result.access_token,
    expires_at: result.expires_in
      ? new Date(Date.now() + Number(result.expires_in) * 1000).toISOString()
      : connection.expires_at,
  }

  await supabase
    .from('calendar_connections')
    .update({
      access_token: updatedConnection.access_token,
      expires_at: updatedConnection.expires_at,
      connection_status: 'Connected',
      updated_at: new Date().toISOString(),
    })
    .eq('provider', 'google')

  return updatedConnection
}

function googleEventPayload(schedule: InterviewSchedule) {
  const start = schedule.scheduled_for ? new Date(schedule.scheduled_for) : new Date()
  const duration = Number(schedule.interview_duration_minutes ?? 30)
  const end = new Date(start.getTime() + duration * 60 * 1000)
  const applicant = schedule.applicants
  const role = applicant?.jobs?.title ?? 'Final interview'

  return {
    summary: `Final interview: ${applicant?.full_name ?? 'Candidate'} - ${role}`,
    location: applicant?.jobs?.location ?? '',
    description: [
      'Generated by ViankaX Hiring Automation Platform.',
      applicant?.phone ? `Candidate phone: ${applicant.phone}` : '',
      schedule.scheduling_url ? `ViankaX scheduling URL: ${schedule.scheduling_url}` : '',
    ].filter(Boolean).join('\n'),
    start: { dateTime: start.toISOString() },
    end: { dateTime: end.toISOString() },
    attendees: [
      applicant?.email ? { email: applicant.email } : null,
      schedule.interviewer_email ? { email: schedule.interviewer_email } : null,
    ].filter(Boolean),
  }
}

async function syncGoogleEvent(
  supabase: ReturnType<typeof createClient>,
  schedule: InterviewSchedule,
  connection: CalendarConnection,
) {
  const refreshedConnection = await refreshGoogleToken(supabase, connection)
  if (!refreshedConnection.access_token) {
    throw new Error('Google access token is missing.')
  }

  if (schedule.sync_status === 'Cancel Ready to Sync' && schedule.external_event_id) {
    const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${schedule.external_event_id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${refreshedConnection.access_token}` },
    })

    if (!response.ok && response.status !== 410 && response.status !== 404) {
      const result = await response.json().catch(() => ({}))
      throw new Error(result?.error?.message ?? 'Google event cancel failed.')
    }

    return { eventId: schedule.external_event_id, syncStatus: 'Cancel Synced', action: 'google_cancel' }
  }

  const payload = googleEventPayload(schedule)
  const hasEvent = Boolean(schedule.external_event_id)
  const response = await fetch(
    hasEvent
      ? `https://www.googleapis.com/calendar/v3/calendars/primary/events/${schedule.external_event_id}`
      : 'https://www.googleapis.com/calendar/v3/calendars/primary/events?sendUpdates=all',
    {
      method: hasEvent ? 'PATCH' : 'POST',
      headers: {
        Authorization: `Bearer ${refreshedConnection.access_token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    },
  )
  const result = await response.json()

  if (!response.ok) {
    throw new Error(result?.error?.message ?? 'Google event sync failed.')
  }

  return { eventId: result.id, syncStatus: 'Synced', action: hasEvent ? 'google_update' : 'google_create' }
}

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

    if (!supabaseUrl || !serviceRoleKey) {
      throw new Error('Missing Supabase function environment variables.')
    }

    const supabase = createClient(supabaseUrl, serviceRoleKey)
    const { data: schedules, error } = await supabase
      .from('interview_schedules')
      .select(`
        id,
        applicant_id,
        provider,
        scheduled_for,
        status,
        sync_status,
        external_event_id,
        scheduling_url,
        interviewer_email,
        interview_duration_minutes,
        buffer_minutes,
        applicants(full_name, email, phone, jobs(title, location))
      `)
      .in('sync_status', ['Ready to sync', 'Update Ready to Sync', 'Cancel Ready to Sync'])
      .limit(25)

    if (error) throw error

    const { data: connections, error: connectionError } = await supabase
      .from('calendar_connections')
      .select('provider, provider_account_email, access_token, refresh_token, expires_at')

    if (connectionError && connectionError.code !== '42P01') throw connectionError
    const connectionMap = new Map((connections ?? []).map((connection: CalendarConnection) => [connection.provider, connection]))
    const processed = []

    for (const schedule of (schedules ?? []) as InterviewSchedule[]) {
      const provider = providerFromSchedule(schedule)
      const connection = connectionMap.get(provider)
      let syncResult = null

      try {
        if (provider === 'google' && connection) {
          syncResult = await syncGoogleEvent(supabase, schedule, connection)
        } else {
          syncResult = {
            eventId: schedule.external_event_id ?? `vx-placeholder-${schedule.id}`,
            syncStatus: schedule.sync_status === 'Cancel Ready to Sync' ? 'Cancel Synced' : 'Synced',
            action: provider === 'internal' ? 'internal_sync' : `${provider}_placeholder_sync`,
          }
        }

        const { error: scheduleError } = await supabase
          .from('interview_schedules')
          .update({
            external_event_id: syncResult.eventId,
            sync_status: syncResult.syncStatus,
            sync_error: null,
            synced_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          })
          .eq('id', schedule.id)

        if (scheduleError) throw scheduleError

        await supabase.from('calendar_sync_logs').insert({
          applicant_id: schedule.applicant_id,
          interview_schedule_id: schedule.id,
          provider,
          action: syncResult.action,
          sync_status: syncResult.syncStatus,
          provider_event_id: syncResult.eventId,
          message: provider === 'google' && connection
            ? 'Google Calendar event synced.'
            : 'Placeholder calendar sync completed. Connect provider OAuth for real external event creation.',
        })

        processed.push({ id: schedule.id, provider, syncStatus: syncResult.syncStatus })
      } catch (syncError) {
        const message = errorMessage(syncError)
        await supabase
          .from('interview_schedules')
          .update({
            sync_status: 'Failed',
            sync_error: message,
            updated_at: new Date().toISOString(),
          })
          .eq('id', schedule.id)

        await supabase.from('calendar_sync_logs').insert({
          applicant_id: schedule.applicant_id,
          interview_schedule_id: schedule.id,
          provider,
          action: 'sync_failed',
          sync_status: 'Failed',
          error_message: message,
        })
      }
    }

    return jsonResponse({
      processed: processed.length > 0,
      processedCount: processed.length,
      message: processed.length
        ? `Synced ${processed.length} pending calendar event${processed.length === 1 ? '' : 's'}.`
        : 'No pending calendar events are ready to sync.',
      events: processed,
    })
  } catch (error) {
    return jsonResponse({ error: errorMessage(error) }, 500)
  }
})
